print("\nTalking to Your Code: Because Yelling at the Screen Doesn’t Work (Yet)\n")
print("This is my learning journey!!")
user = input("Username : ")
feedback = input("FeedBack : ",)
star = int(input("How many star : "))
print("\n",user," ~ ", feedback)
print("\t",star*"* ")
print("\n Nandu ~ Thanks! for the feedback.")
